//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub product_id: i32,
    pub name: String,
    pub price: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::product::Entity",
        from = "Column::ProductId",
        to = "super::product::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Product,
}

impl Related<super::product::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Product.def()
    }
}
// --Additional Implementations --------------------------------
#[derive(Debug, Serialize, Deserialize)]
pub struct CreateItemInput {
    pub product_id: i32,
    pub name: String,
    pub price: Decimal,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct UpdateItemInput {
    pub name: Option<String>,
    pub price: Option<Decimal>,
}

// ------------------------------------------------------------

impl ActiveModelBehavior for ActiveModel {}
