name: Build and Deploy to Google Cloud Run

env:
  SERVICE_NAME: product-item-microservice
  PROJECT_ID: my-microservice-444912
  DOCKER_IMAGE_URL: us-central1-docker.pkg.dev/my-microservice-444912/product-item-microservice/my-pimi1:latest

on:
  push:
    branches:
      - main  # or any other branch
  pull_request:
    branches:
      - main

jobs:
  dockerize_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Google Cloud Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: my-microservice-444912
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest .
        docker push ${{ env.DOCKER_IMAGE_URL }}:latest || echo "Failed to push the image"
    - name: Deploy to Cloud Run
      run: |
        echo SERVICE_NAME $SERVICE_NAME
        gcloud run deploy $SERVICE_NAME --image ${{ env.DOCKER_IMAGE_URL }}:latest --platform managed --region us-central1 --allow-unauthenticated

